server:
  port: 8181
spring:
  application:
    name: LargeData-DataProcessor-Module
  profiles:
    active:
      - dev
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
application:
  #    mode: normal
  mode: memory-efficient
